### ISSUE TITLE
Method prepareUpdateData does not exist 

### ISSUE THREAD

**Issue by arlin2050** [simplethings/EntityAudit#111]
Hi,

when I use EntityAudit and SoftDeleteable on the same entity and I remove this entity, I got this error :

ReflectionException: Method prepareUpdateData does not exist in SimpleThings/EntityAudit/EventListener/LogRevisionsListener.php line 114

Seems that entityAudit is launched two times and the second time I got this error. Also, putting this on line 114 resolves the issue but I don't know the consequences : 
``` php
if (!$persisterR->hasMethod('prepareUpdateData')) {
      continue;
}
```

Thanks !

**Comment by andrewtch** [comment]
Hi,

can you give your example entity? Thanks!

**Comment by arlin2050** [comment]
Here is the mapping : 
``` xml
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd"
        xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping" >
    <entity name="Oru\Bundle\CustomBundle\Entity\Demande" table="oru_custom_demande" repository-class="Oru\Bundle\CustomBundle\Entity\DemandeRepository" >
        <id name="id" type="integer" column="id">
            <generator strategy="AUTO"/>
        </id>
        <field name="statut" type="string" length="20" nullable="true" />
        <field name="deletedAt" column="deleted_at" type="datetime" nullable="true" />
        <gedmo:soft-deleteable field-name="deletedAt" />
    </entity>
</doctrine-mapping>
```

And the EntityAudit configuration : 
```yaml
simple_things_entity_audit:
    audited_entities:
        - Oru\Bundle\CustomBundle\Entity\Demande
```

The php class for this entity is auto-generated via doctrine :
```php
namespace Oru\Bundle\CustomBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

class Custom {

    /**
     * @var integer
     */
    private $id;

     /**
     * @var string
     */
    protected $statut;

    /**
     * @var \DateTime
     */
    private $deletedAt;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * @param string $statut
     */
    public function setStatut($statut)
    {
        $this->statut = $statut;
    }

    /**
     * @return string
     */
    public function getStatut()
    {
        return $this->statut;
    }

    /**
     * Set deletedAt
     *
     * @param \DateTime $deletedAt
     * @return Demande
     */
    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;
    
        return $this;
    }

    /**
     * Get deletedAt
     *
     * @return \DateTime 
     */
    public function getDeletedAt()
    {
        return $this->deletedAt;
    }
}
```
Thanks !

**Comment by andrewtch** [comment]
@arlin2050 , as you can see in #113, everything works fine (however your use case allowed to find at least one bug).

It seems I can not repeat your issue. Can you update doctrine / EA to latest versions and check again? Can you provide a test that 100% repeats the issue?

Thanks!

**Comment by arlin2050** [comment]
Thanks for the reply. I'll try to update doctrine and check again.

**Comment by andrewtch** [comment]
@arlin2050 , what's the status on this? )

**Comment by arlin2050** [comment]
Hi,

My doctrine/orm version is v2.3.6. It's the latest possible version of doctrine for my installation which depends on Symfony 2.3 LTS.
EntityAudit version is up to date with dev-master.

Lauching unit tests, I've got two errors :
1) SimpleThings\EntityAudit\Tests\IssueTest::testIssue111
ReflectionException: Method prepareUpdateData does not exist

vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/EventListener/LogRevisionsListener.php:114
vendor/doctrine/common/lib/Doctrine/Common/EventManager.php:59
vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:364
vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:355
vendor/simplethings/entity-audit-bundle/tests/SimpleThings/Tests/EntityAudit/IssueTest.php:75

2) SimpleThings\EntityAudit\Tests\IssueTest::testIssue9
ReflectionException: Method prepareUpdateData does not exist

vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/EventListener/LogRevisionsListener.php:114
vendor/doctrine/common/lib/Doctrine/Common/EventManager.php:59
vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:364
vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:355
vendor/simplethings/entity-audit-bundle/tests/SimpleThings/Tests/EntityAudit/IssueTest.php:146

Thanks

**Comment by andrewtch** [comment]
Ok, please see #115, this should fix the issue.

**Comment by arlin2050** [comment]
Applying the three commits available in #115, I've got this error : 

```
FatalErrorException: Error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/EventListener/LogRevisionsListener.php line 160
```
Real exception is : 
```
Could not resolve database type for column "deleted_at" during extra updates
```

I've got this error because I use the property name on a column, and my column deletedAt in database is not camel case but 'deleted_at'. Maybe another issue ?
Thanks

**Comment by andrewtch** [comment]
Still the same entity yet with ```@Column(type="datetime", name="deleted_at")``` ?

**Comment by andrewtch** [comment]
...anyway, please check #116 )

**Comment by arlin2050** [comment]
> Still the same entity yet with @Column(type="datetime", name="deleted_at") ?
Yes

**Comment by arlin2050** [comment]
> ...anyway, please check #116 )

It works, thanks.
When will this be available on master ?

**Comment by andrewtch** [comment]
it's already merged into master.
