### ISSUE TITLE
Add a field to the revisions table

### ISSUE THREAD

**Issue by Tomsgu** [simplethings/EntityAudit#122]
Hi,

After a long time I found your very good bundle. I did a history audit by myself, but it's not as flexible as I want, that's why I started to look for another solution.

I need to store one more field in a revision table ("is_valid" field - user can change an entity, but it has to be validated by admin). Is there some way how to add it to the revision table?

**Comment by aivus** [comment]
See #93

**Comment by Tomsgu** [comment]
Thank you Aivus!
