### ISSUE TITLE
Foreign key diff

### ISSUE THREAD

**Issue by Tomsgu** [simplethings/EntityAudit#123]
Hi everyone,

Is there any change to see also foreign key changes?

Thank you in advance!

**Comment by andrewtch** [comment]
Hi, what do you mean by "foreign key changes"?

**Comment by Tomsgu** [comment]
Hi thank you for reply, I am sorry for not specifying well. 

I need to see changes between e.g. customField - person (oneToMany). When I delete connection between these two entities. The bundle realize it and creates customField entityRevision. When I compare customField rev.1 and rev.2 nothing was changed. 

Field | Deleted | Same | Updated
-------|------------|----------|------------
id     | - | 1 | -	
attribute | - |	Phone	| -
is_valid | - | - | -

Is there possibility to see also person_id changes?

**Comment by andrewtch** [comment]
Ok, I thing I got you ) I'll finish some other PR's and take a look on this part of code soon.
