### ISSUE TITLE
revtype in revisions-table instead of in the audit-table?

### ISSUE THREAD

**Issue by targodan** [simplethings/EntityAudit#132]
Just an Idea...
Wouldn't it be better to store the revtype (UPD/INS/DEL) in the revisions table instead of the audit table?

Since revid -> revtype it would make more sence looking at it in a relational way (normalization?).

In my latest project I would like to provide a table of all revisions including the revtype but ideally without retrieving the whole revision. Saving the revtype in the revisions table would spare me some nasty workarounds/hacks for that.

I know it would be quite a change for the API but in my oppinion it would be worth it. What do you think?

**Comment by StrikeForceZero** [comment]
I too would like this. The revision object should have this has a property not the audited entity

**Comment by StrikeForceZero** [comment]
I've implemented this in a [fork of the project](https://github.com/StrikeForceZero/EntityAudit/commit/5171463a38e8d75824e56e4cb1fd28587eb7ddd3). 

(fair warning that the other previous [commit](https://github.com/StrikeForceZero/EntityAudit/commit/fc1b9fda7bc729c9cd4f03370e2232972aa2d86b) in my fork: ArrayDiff has a different signature and could be a breaking api change)

**Comment by soerenbernstein** [comment]
This will not do because a revision can include multiple entities which could have different revtypes. As for example you have a group of people and add a new  - as in not already in your db - person, the person entity would have a revtype 'INS' where as the group entity will have a revtype of 'UPD'.
