### ISSUE TITLE
Get list of entities, that are currently set for revisions

### ISSUE THREAD

**Issue by PriaBrock** [simplethings/EntityAudit#136]
Hi,

I would like to have possibility to check which entities are set for revisioning. Right now I can set them in the "simplethings_entityaudit.config" service, but I cannot get them. Is it possible somehow?

Thanks for any advice

**Comment by Renrhaf** [comment]
Hello @PriaBrock,

you can get the "audited_entities" from the container parameter called : "simplethings.entityaudit.audited_entities".
```
$container->getParameter("simplethings.entityaudit.audited_entities");
```
