### ISSUE TITLE
Audit log not updated for certain actions

### ISSUE THREAD

**Issue by benoliver999** [simplethings/EntityAudit#142]
I have an action that calls upon an Entity's repository, which has a function running a DQL query.

It does a simple -1 on a record in the DB. This is the controller:

    public function checkoutAction($id)
        {
    $em = $this->getDoctrine()->getManager();
    $article20000stock = $em->getRepository('RegenerysQMSBundle:Article20000Stock')
         ->findAndCheckOut($id);
    return $this->redirect($this->generateUrl('regenerys_qms_article20000stock_individual', array('id' => $id)));
    }

And this is the repo:

    public function findAndCheckOut($id)
         {
            return $this->getEntityManager()
                ->createQuery(
        'UPDATE RegenerysQMSBundle:Article20000Stock s
    SET 
        s.unitsInStock = s.unitsInStock - 1
    WHERE
        s.id = :id'
                 )->setParameter('id', $id)
                ->getSingleResult();
        }

Whenever I run this, the DB gets updated, but it's not recorded in the audit log.

The Entity is listed in my config, and I have an 'edit' action that works just fine, but it's not in the repo.

Am I doing something wrong?

**Comment by DavidBadura** [comment]
Hi

this isn't an entity audit issue but a doctrine orm limitation. see http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#update-queries

if you use DQL to update your entities, doctrine don't fire any events, so entity audit can't notice this.

in short: it isn't supported, sorry :-) you should update your entity objects and avoid DQL for updates or deletes.

**Comment by benoliver999** [comment]
But my beloved queries! Oh well, not the end of the world, and easy enough
to adapt. Thanks for the heads up on this, I had a hunch this might have
been the issue but would not have found the explanation.

On 15 July 2015 at 14:46, David Badura <notifications@github.com> wrote:

> Hi
>
> this isn't an entity audit issue but a doctrine orm limitation. see
> http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#update-queries
>
> if you use DQL to update your entities, doctrine don't fire any events, so
> entity audit can't notice this.
>
> in short: it isn't supported, sorry :-) you should update your entity
> objects and avoid DQL for updates or deletes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simplethings/EntityAudit/issues/142#issuecomment-121621623>
> .
>



-- 
benoliver999.com
