### ISSUE TITLE
Error when using PostgreSQL

### ISSUE THREAD

**Issue by phackwer** [simplethings/EntityAudit#147]
I have always used the EntityAuditBundle on MySQL, MSSQL and Oracle databases and never had any problem. But currently I'm using PostgreSQL with a client and I found a small bug due to a problem that occurs with PDO-PgSQL and the lastInsertId implementation.

The bug always return this error:

[2015-09-21 10:47:43] doctrine.DEBUG: "START TRANSACTION" [] []
[2015-09-21 10:47:43] doctrine.DEBUG: UPDATE tb_proj_project SET ds_name = ?, fl_active = ? WHERE co_project = ? ["Projeto de teste - 4","1",4] []
[2015-09-21 10:47:43] doctrine.DEBUG: INSERT INTO tb_audit_revision (timestamp, username) VALUES (?, ?) ["2015-09-21 10:47:43","1"] []
[2015-09-21 10:47:43] doctrine.DEBUG: "ROLLBACK" [] []
[2015-09-21 10:47:44] request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  currval of sequence "revisions_id_seq" is not yet defined in this session" at /usr/local/apache2/htdocs/mma/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 955 {"exception":"[object] (PDOException(code: 55000): SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  currval of sequence \"revisions_id_seq\" is not yet defined in this session at /usr/local/apache2/htdocs/mma/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:955)"} []

That's due the fact that currval() DOES NOT bring any value if nextval has not been explicit used.

http://www.postgresql.org/docs/9.4/static/functions-sequence.html

"currval

Return the value most recently obtained by nextval for this sequence in the current session. (An error is reported if nextval has never been called for this sequence in this session.) Because this is returning a session-local value, it gives a predictable answer whether or not other sessions have executed nextval since the current session did."

What shown me how to fix this problem was this small post on the internet:

http://stackoverflow.com/questions/10492566/lastinsertid-does-not-work-in-postgresql

Line 287 of the LogRevisionsListener mades a small mistake and passes the name of the sequence used on the last insert, but the truth is that, despite of PostgreSQL being a DB that supports sequences, the PDO driver already handle this for us, being unecessary to send the sequence name for the lastInsertId() method. When you do this, the PDO PgSQL driver tries to run a currval() on the sequence, but a nextval has never been called because the serial datatype acts like an autoincrement type. Being so, PostgreSQL ALWAYS throws an error.

**Comment by phackwer** [comment]
New observation:

For this to work, you need to allow OIDs to be created.

This means your SQL for the revisions table should be as follows:

CREATE TABLE revisions (id SERIAL NOT NULL UNIQUE, timestamp TIMESTAMP  NOT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY (id) );

**Comment by phackwer** [comment]
Here's final and tested code (earlier code sent worked... only for the first audit!).

    private function getRevisionId()
    {
        if ($this->revisionId === null) {
            $this->conn->insert($this->config->getRevisionTableName(), array(
                'timestamp' => date_create('now'),
                'username' => $this->config->getCurrentUsername(),
            ), array(
                Type::DATETIME,
                Type::STRING,
            ));

            $connParams = $this->conn->getParams();
            if (strstr($connParams['driver'], 'pgsql')) {
                $lastVal = $this->conn->query('SELECT LASTVAL()')->fetch();
                $this->revisionId = $lastVal['lastval'];
            } else {
                $sequenceName = ($this->platform->supportsSequences() && !$isPg)
                ?  $this->platform->getIdentitySequenceName($this->config->getRevisionTableName(), 'id')
                : null;

                $this->revisionId = $this->conn->lastInsertId($sequenceName);
            }
        }
        return $this->revisionId;
    }

**Comment by bendavies** [comment]
@phackwer This looks like it might have been fixed by https://github.com/simplethings/EntityAudit/commit/912303e7e35d4b901522e2acee797ca5fbe13865

As of https://github.com/simplethings/EntityAudit/pull/209, the testsuite runs again postgres 9.1-9.4.

I'm going to close this but please reopen if you are still having problems.
