### ISSUE TITLE
Release new tag

### ISSUE THREAD

**Issue by Rvanlaak** [simplethings/EntityAudit#148]
We keep on getting deprecation notices because https://github.com/simplethings/EntityAudit/commit/e8696b4bf8937c2b6dd2a07914cd5b244707ab75 was not in a stable release yet. Can you release a new tag?

**Comment by TomasVotruba** [comment]
That would be a great idea! Last tag was about a year ago.

**Comment by DavidBadura** [comment]
I have to look why the build fails before I can do it. :-/

**Comment by Rvanlaak** [comment]
See you're working on it, so :+1:

**Comment by smoench** [comment]
a new tag has been [released](https://github.com/simplethings/EntityAudit/releases)

**Comment by Rvanlaak** [comment]
:+1:  https://github.com/simplethings/EntityAudit/pull/155#issuecomment-149210849

**Comment by TomasVotruba** [comment]
Great job! Thanks!
