### ISSUE TITLE
Wrong Type Hint for EntityManager 

### ISSUE THREAD

**Issue by igst** [simplethings/EntityAudit#149]
Hi!

If a custom EntityManager Decorator is used, AuditManager->createAuditReader() and AuditReader::__construct() throwing exceptions because of 'EntityManager' Type Hint: 

*Catchable Fatal Error: Argument 1 passed to SimpleThings\EntityAudit\AuditReader::__construct() must be an instance of Doctrine\ORM\EntityManager, instance of ACME\Bundle\SomeBundle\Doctrine\EntityManagerDecorator given*

and 

*Catchable Fatal Error: Argument 1 passed to SimpleThings\EntityAudit\AuditManager::createAuditReader() must be an instance of Doctrine\ORM\EntityManager, instance of ACME\Bundle\SomeBundle\Doctrine\EntityManagerDecorator given*

I think it would be better to use 'EntityManagerInterface' instead. 

Thanks!

**Comment by tolry** [comment]
Sounds about right - would you mind creating a PR?

**Comment by TomasVotruba** [comment]
This can be closed now

**Comment by DavidBadura** [comment]
thank you :)

**Comment by OskarStark** [comment]
:+1:
