### ISSUE TITLE
Impossible to create trigger for revisions table on Oracle

### ISSUE THREAD

**Issue by franek** [simplethings/EntityAudit#15]
On Oracle database, it is not possible to create the trigger for the table REVISIONS because EntityAudit uses a reserved word (see http://docs.oracle.com/cd/B19306_01/em.102/b40103/app_oracle_reserved_words.htm).

When I try to create the trigger, I obtain this error : 

CREATE TRIGGER REVISIONS_AI_PK
   BEFORE INSERT
   ON REVISIONS
   FOR EACH ROW
DECLARE
   last_Sequence NUMBER;
   last_InsertID NUMBER;
BEGIN
   SELECT REVISIONS_SEQ.NEXTVAL INTO :NEW.id FROM DUAL;
   IF (:NEW.id IS NULL OR :NEW.id = 0) THEN
      SELECT REVISIONS_SEQ.NEXTVAL INTO :NEW.id FROM DUAL;
   ELSE
      SELECT NVL(Last_Number, 0) INTO last_Sequence
        FROM User_Sequences
       WHERE Sequence_Name = 'REVISIONS_SEQ';
      SELECT :NEW.id INTO last_InsertID FROM DUAL;
      WHILE (last_InsertID > last_Sequence) LOOP
         SELECT REVISIONS_SEQ.NEXTVAL INTO last_Sequence FROM DUAL;
      END LOOP;
   END IF;
END;;
Rapport d'erreur :
ORA-06552: PL/SQL: Compilation unit analysis terminated
ORA-06553: PLS-320: déclaration de type de cette expression est incomplète ou mal structurée
06552. 00000 -  "PL/SQL: %s"
*Cause:    
*Action:

A solution is to replace the timestamp column name. For details, see http://www.lattimore.id.au/2007/03/09/ora-06552-plsql-compilation-unit-analysis-terminated/

**Comment by andrewtch** [comment]
@franek , sorry for necroposting, but can you still confirm this? )

**Comment by franek** [comment]
I can't confirm this anymore. Sorry.

**Comment by andrewtch** [comment]
Clothing then, reopen if you can repeat the issue. Thanks.
