### ISSUE TITLE
how to set a username when loading fixtures?

### ISSUE THREAD

**Issue by OskarStark** [simplethings/EntityAudit#160]
Hi

i would like to set Username "System" or "Importer Foo" on the CLI, when creating entities via a Command or anything else.

Is this possible?

Best,
Oskar

**Comment by smoench** [comment]
You can set the current username on the `AuditConfiguration`:
```php
$container->get('simplethings_entityaudit.config')->setCurrentUsername('beberlei');
```

https://github.com/simplethings/EntityAudit#setting-the-current-username

**Comment by OskarStark** [comment]
Thank you @smoench
