### ISSUE TITLE
TablePrefix breaks TableName with 'schema'

### ISSUE THREAD

**Issue by smoench** [simplethings/EntityAudit#166]
https://github.com/simplethings/EntityAudit/pull/155#discussion_r48649991
tolry on 31 Dec 2015:
> Doesn't this concatination need to be done before prefixing the schema name?
> Else you might end up having $tablePrefix.$schemaName.$tableName.$tableSuffix

https://github.com/simplethings/EntityAudit/blob/master/src/SimpleThings/EntityAudit/AuditConfiguration.php#L58 has to be fixed

**Comment by DavidBadura** [comment]
@smoench we removed the support for ORM 2.4. 

https://github.com/simplethings/EntityAudit/commit/49f9454ca0c49a740a048c4b1fc8a6423cf3f977 and https://github.com/simplethings/EntityAudit/commit/142847ad21a52d07598659eefc522a803428a22a

Do we have a todo here? If yes, can you create a PR to fix this?
