### ISSUE TITLE
SF2.7: Undefined property: appDevDebugProjectContainer::$config

### ISSUE THREAD

**Issue by thomasbeaujean** [simplethings/EntityAudit#175]
In SF 2.7.9, I updated the bundle and get the error:

Notice: Undefined property: appDevDebugProjectContainer::$config 
vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/AuditManager.php at line 44

This come from the factory syntax intruced by the commit 612416e0741225354e3b6ddb9f74dcb3c0ecdabb

The service should be used instead of the class

**Comment by tolry** [comment]
fixed in #176 - I will close this, as soon as I've tagged a new release

**Comment by tolry** [comment]
I just released 0.9.1 - give it a try
https://github.com/simplethings/EntityAudit/releases/tag/0.9.1
