### ISSUE TITLE
When using with Oracle, getting an index name is too long error

### ISSUE THREAD

**Issue by mmucklo** [simplethings/EntityAudit#184]
This is the sort of error I'm getting trying to setup entity audit on an existing entity.

Any suggestions?

```
[Doctrine\DBAL\Exception\DriverException]                                                                              
  An exception occurred while executing 'CREATE INDEX rev_5ad37a6295432926e7c6da0266acbad3_idx ON SOME_TABLE_audit (rev)':  
  ORA-00972: identifier is too long
```

**Comment by tolry** [comment]
@mmucklo looks like you are using Oracle as DBMS, correct? I am not sure, if there are any users out there, using EntityAudit with Oracle.

But in theory this shouldn't be a problem, I would think. At first glance, this looks like being a general doctrine problem, since I would think that the doctrine SchemaManager is responsible for creating the SQL which throws the exception.

Anyone's got an idea, how the unique part of the index name (which seems to be too long for Oracle) is generated in doctrine?

/cc @DavidBadura @smoench

**Comment by smoench** [comment]
it looks like #181 has introduced this failure

**Comment by tolry** [comment]
@smoench thanks for digging that up - leaving the index name empty should have been sufficient there, the addIndex method does generate a unique index name automatically.

Changing this now might trigger unecessary database migrations for users upgrading - so a bit BC "breaky".

@mmucklo do you have a test installation where you can verify that changing the call in line 101 of "src/SimpleThings/EntityAudit/EventListener/CreateSchemaListener.php" to

```php
$revisionTable->addIndex(array($this->config->getRevisionFieldName()));
```

will fix your use case?

**Comment by mmucklo** [comment]
Yes.

I can try testing it and get back to you early next week.

**Comment by mmucklo** [comment]
Index creation now works.

BTW the rest of the schema creation is pretty nasty - I'm not quite sure how to fit it into a migration just yet...

(slightly edited version below)
```
CREATE TABLE BLAH_audit (id NUMBER(10) NOT NULL, rev NUMBER(10) NOT NULL, something VARCHAR2(20) DEFAULT NULL NULL, something_else VARCHAR2(255) DEFAULT NULL NULL, custom1_blah CLOB DEFAULT NULL NULL, custom2_blah CLOB DEFAULT NULL NULL, created_by VARCHAR2(255) DEFAULT NULL NULL, updated_by VARCHAR2(255) DEFAULT NULL NULL, created_at TIMESTAMP(0) DEFAULT NULL NULL, updated_at TIMESTAMP(0) DEFAULT NULL NULL, revtype VARCHAR2(4) NOT NULL, PRIMARY KEY(id, rev));
CREATE INDEX IDX_8FA975549D82EC7 ON BLAH_audit (rev);
COMMENT ON COLUMN BLAH_audit.custom1_blah IS '(DC2Type:json_array)';
COMMENT ON COLUMN BLAH_audit.custom2_blah IS '(DC2Type:simple_array)';
CREATE TABLE revisions (id NUMBER(10) NOT NULL, timestamp TIMESTAMP(0) NOT NULL, username VARCHAR2(255) NOT NULL, PRIMARY KEY(id));
DECLARE
  constraints_Count NUMBER;
BEGIN
  SELECT COUNT(CONSTRAINT_NAME) INTO constraints_Count FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'REVISIONS' AND CONSTRAINT_TYPE = 'P';
  IF constraints_Count = 0 OR constraints_Count = '' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE REVISIONS ADD CONSTRAINT REVISIONS_AI_PK PRIMARY KEY (ID)';
  END IF;
END;;
CREATE SEQUENCE REVISIONS_SEQ START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE TRIGGER REVISIONS_AI_PK
   BEFORE INSERT
   ON REVISIONS
   FOR EACH ROW
DECLARE
   last_Sequence NUMBER;
   last_InsertID NUMBER;
BEGIN
   SELECT REVISIONS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   IF (:NEW.ID IS NULL OR :NEW.ID = 0) THEN
      SELECT REVISIONS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   ELSE
      SELECT NVL(Last_Number, 0) INTO last_Sequence
        FROM User_Sequences
       WHERE Sequence_Name = 'REVISIONS_SEQ';
      SELECT :NEW.ID INTO last_InsertID FROM DUAL;
      WHILE (last_InsertID > last_Sequence) LOOP
         SELECT REVISIONS_SEQ.NEXTVAL INTO last_Sequence FROM DUAL;
      END LOOP;
   END IF;
END;;
```

**Comment by mmucklo** [comment]
any update on when this fix might be committed?

**Comment by mmucklo** [comment]
Just an update, so rolling back to the commits before #181 seems to fix things partially (aside from the crazy SQL above).

It inserts if I do:

```
bin/console doctrine:schema:update --force
```

However it seems to want to do an ALTER TABLE there on after

```
bin/console doctrine:schema:update --dump-sql
ALTER TABLE REVISIONS MODIFY (id NUMBER(10) DEFAULT NULL);
```

If you do another:
```
bin/console doctrine:schema:update --force
```

You still get the same thing again when you run a --dump-sql:

```
bin/console doctrine:schema:update --dump-sql
ALTER TABLE REVISIONS MODIFY (id NUMBER(10) DEFAULT NULL);
```

There's another oracle bug I found, but I'll open another radar.

**Comment by DavidBadura** [comment]
I think we can truncate the md5 hash. 8 chars should be enough.

**Comment by smoench** [comment]
This would be the solution: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/AbstractAsset.php#L219
