### ISSUE TITLE
User identifier may change multiple times during execution - rely on a dynamic factory for it instead?

### ISSUE THREAD

**Issue by Ocramius** [simplethings/EntityAudit#187]
During an app's lifecycle, many things can go wrong with auth + business logic.

 * email auto-login + action (via JWT token or similar) causes anonymous -> logged in upgrade + business interaction
 * `sudo` -alike actions cause user privilege change mid-request
 * auto-logout caused by business logic (violations, usually), lead to logged in -> anonymous downgrade

Therefore, `AuditConfiguration#setCurrentUsername()` seems to be insufficient to deal with that.

Assuming (big assumption tho!) that there is somewhere a storage keeping the current logged in user in memory, it is easy to change the logic to accomodate this, by having a `AuditConfiguration#setCurrentUsernameProvider(callable $usernameProvider)`. That way, each time the username is required, the provider is called, making sure the interactions are executed with the correct role at every transaction within the lifecycle of a request.

**Comment by tolry** [comment]
First things first: this module is not actively developed nor actively maintained at the moment. We have no one around with intimate knowledge of the code base. Sorry for that :-(

That being said: I very much agree, this is definitely a problem not yet adressed. Having a dynamic way to determine the current user would be much safer and might probably be fixable without any BC breaks.

@Ocramius would you like to make a little prototype?

/cc @DavidBadura @andrewtch @smoench any thoughts on this?

**Comment by Ocramius** [comment]
> First things first: this module is not actively developed nor actively maintained at the moment. We have no one around with intimate knowledge of the code base. Sorry for that :-(

no big deal

 > @Ocramius would you like to make a little prototype?

Depends on whether I'll need it over the next few weeks. For now I added a big fat `@TODO this is a huge assumption, and it relies on the app staying as simple as it currently is`

**Comment by bendavies** [comment]
@Ocramius can you take a look at #210. Thanks

**Comment by Ocramius** [comment]
@bendavies provided review, thanks for the PR!
