### ISSUE TITLE
[RFC] Supports Api-Platform

### ISSUE THREAD

**Issue by Simperfit** [simplethings/EntityAudit#193]
Hi, 

I have been working on a project using api-platform to generate the api and we made a bridge between api-platform and this bundle.

Do you want to integrate this bridge ? It's ready to use and I could make an PR for that, this generate an api using the history of one entity

**Comment by DavidBadura** [comment]
Sorry, but we do not have the resources to maintain further integrations. The plan is to split this project in a library and bundle. If we are done with it, then we can see if someone wants to maintain it.
