### ISSUE TITLE
Fields that require SQL conversion to convert to database value not converted when saving to the audit table.

### ISSUE THREAD

**Issue by jamescdavis** [simplethings/EntityAudit#196]
When an audited entity contains a field with a custom mapping type that requires calling a SQL function to convert to a value suitable for the database column, EntityAudit is not performing the SQL conversion when saving the field value to the audit table. The original, unconverted value is stored instead.

**Comment by whyte624** [comment]
If audited entity contains the same field, there will be an error in `\SimpleThings\EntityAudit\AuditReader::find`. So viewing audited entity is not possible.
Can you please apply similar changes to AuditReader service?
