### ISSUE TITLE
Configure behaviour to only create revisions?

### ISSUE THREAD

**Issue by edrush** [simplethings/EntityAudit#200]
Hi,

I have an API through which I want to allow for adding new revisions to an entity, which can later be merged into the entity tables by an editor (person).

Right now using SimpleThingsEntityAuditBundle causes revisions to be created and the original entities to be updated at once, so the last revision of an entity hast the same data as the entity itself - right?

Can this behaviour be changed so that only new revisions will be created but the original data in the table stays the same? Or how could I make this happen? Changing the behaviour to revert entities on update seems to prevent from stopping revisions.

Regards!

**Comment by DavidBadura** [comment]
Sorry, this isn't the scope of entity audit.
