### ISSUE TITLE
RFC: drop support for PHP < 5.6

### ISSUE THREAD

**Issue by bendavies** [simplethings/EntityAudit#207]
Hey,

It looks like this library still supports all php versions back to 5.3.
Since versions < 5.6 are end of life, i propose dropping support for them.

cc @simplethings/entityaudit

**Comment by DavidBadura** [comment]
:+1: I think this is a good idea.

**Comment by tolry** [comment]
:+1: but only after tagging a version that still supports 5.3

**Comment by bendavies** [comment]
sounds good. I will finish fixing the mysql/postgres bugs, and we can tag.

**Comment by atufkas** [comment]
Hello Dev-Team,

first of all: Thank you for maintaining a project of great quality and benefit! 

I have mixed emotions on this issue. I guess there are zillions of discussions pro and contra supporting end-of-life or unsupported versions of PHP. And, if just speaking for myself and integrations I maintain on my own in my own little infrastructure space, I'd definitely be with you and say: Go for it!

But the truth is: Not supporting older versions, even if they are already EOL, locks out a whole bunch of people and companies running integrations in "legacy environments" of a kind that are not easily migrated from one language version to the next every year. For whatever reason, that's for sure another interesting discussion. But let's accept it as a fact. I've constantly experienced this (and problems related to it) in so many companies I've worked for over the past 20 years.

So my point is: If there's no urgent need to make use of new language features AND if there are no  dependencies on libs that themselves demand at least PHP 5.6: Why dropping support for older language versions? People can still choose which version to run on and it's completely in their responsibility regarding security issues, bugs, performance and so on.

Just my 2 cents.

**Comment by rvanlaak** [comment]
I think the minimum PHP versions of all dependencies should also be taken into account. In other words, if `doctrine/dbal` is bumped, then that PHP version also should be taken into account.

Just some info; right now the Doctrine PHP version used actually also is `>=5.3.2`, see https://packagist.org/packages/doctrine/orm#v2.4.8 and https://packagist.org/packages/doctrine/dbal#v2.5.5

`doctrine/orm: v.2.5.5` actually is on `PHP >=5.4`, so if ORM would be bumped the PHP version over here also should be raised: https://packagist.org/packages/doctrine/orm#v2.5.5

Oh, I also see the bundle does not rely on Symfony, which is nice! Most `README.md` chapters actually assume that Symfony is used, so completely offtopic but I think that could be split too ;)

**Comment by Soullivaneuh** [comment]
> locks out a whole bunch of people and companies running integrations in "legacy environments"

@atufkas You said it: "legacy environments".

In this case, they indeed have to use a legacy version of this package. This is why I also agree with @tolry comment.

But this make no sense to continue application development and want to use new feature of dependencies without resolving the PHP version issue first.

Concerning doctrine, I heard that the legacy PHP version dropping will be faster than past.

v2.7 of doctrine/common already need PHP 5.6 as minimum: https://github.com/doctrine/common/blob/v2.7.1/composer.json#L16

**Comment by rvanlaak** [comment]
Okay, 👌 for `5.6` after tagging latest stable for `5.3`.

**Comment by atufkas** [comment]
@Soullivaneuh Okay okay okay... go for tagging a latest stable supporting 5.3. 👍

**Comment by rvanlaak** [comment]
Whoop @DanielBadura I see you tagged `v1.0.0` yesterday, just before mergin #239 

Will that also mean that the next version also will be tagged `v2.0.0`? https://github.com/composer/composer/issues/4090#issuecomment-107392631

Had a discussion about this lately, some think that bumping PHP up could also just be a minor release as it does not really break anythink.

**Comment by DavidBadura** [comment]
yes, the next version will be 2.0. See https://github.com/simplethings/EntityAudit/issues/203
