### ISSUE TITLE
Wrong relations returned for bidirectional audited relationships (OneToOne)

### ISSUE THREAD

**Issue by peschee** [simplethings/EntityAudit#217]
We've just discovered a problem in an application we're building with this bundle. For bidirectional OneToOne relationships, where both sides of the relation are audited, the `AuditReader` returns wrong data.

Let's say you have relationships set up as follows:
- DataContainer (owning side) → Data
- Data → DataContainer

Querying for an entity version of either `DataContainer` or `Data` will return a wrong relationship, when the relationship is accessed THROUGH the related entity, such as:

DataContainer (1) → Data (2) → DataContainer (3)

The entity in (3) is, in our case, always wrong. The problem is somewhere in the `createEntity` and `find` method in the `AuditReader` class. The relationship from (2) to (3) SHOULD be queried by the foreign key for Data in DataContainer. However, the foreign key gets lost inside the `find` method somewhere around here

`$values = array_merge(array($revision), array_values($id));`

I've tried to illustrate this with an example in a separate branch with a failing test:

https://github.com/peschee/EntityAudit/tree/failing_one_to_one_bidirectional

Particularly in this commit:

https://github.com/peschee/EntityAudit/commit/5cb53984772dcabf31130f10e8ba7fd99baefa2f

Any ideas / pointers on how to fix this?

**Comment by peschee** [comment]
We've added a fix for this in a separate branch

https://github.com/peschee/EntityAudit/tree/failing_one_to_one_bidirectional_fix

in this commit

53f76f4c914cda2467844e7b17b0ca2b446951b2

All tests including our test that failed before work now. However, this touches the `find` method so we're not quite sure if this is the right way. Maybe @bendavies or @andrewtch can have a look? /cc @jfierz

**Comment by bendavies** [comment]
Can you submit a PR with test and fix, and i'll take a look

**Comment by peschee** [comment]
Done
