### ISSUE TITLE
Unable to parse auditable.xml after b5be02a

### ISSUE THREAD

**Issue by pedropapa** [simplethings/EntityAudit#220]
After updating EntityAudit to the latest dev-master version, I receive this error after running app/console cache:clear command:

```
Clearing the cache for the prod environment with debug false

                                                                                                                                                                                    
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                                        
Unable to parse file "/var/www/html/homolog/antt-qa/vendor/simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/DependencyInjection/../Resources/config/auditable.xml".
```  

I think it's a bug from EntityAudit, can you please fix it?

**Comment by DavidBadura** [comment]
Can you try to remove your cache folder manually? Can you tell me afterwards whether that solved your problem?

**Comment by pedropapa** [comment]
Still having the same issue after removing caches manually. I can confirm that downgrading the bundle to commit 86c5d0cf6db31ba4277e6c5256696204c9346bcb the application works fine.

More info:
PHP version: 5.3
Symfony version: 2.5.12

**Comment by smoench** [comment]
@pedropapa `dev-master` is not compatible with symfony `<2.7`, please use version `~0.9`. By the way https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md

**Comment by tolry** [comment]
@smoench shouldn't have composer caught that and refuse to install this version with symfony < 2.7?

**Comment by pedropapa** [comment]
0.8 version of EntityAudit seems to be the most recent version that does have compatibility with Symfony 2.5.12, I just installed it and everything is working fine for now.
