### ISSUE TITLE
1.0 - todos

### ISSUE THREAD

**Issue by tolry** [simplethings/EntityAudit#225]
as suggested in #203 

Version 1.0
- what's missing?
- what needs to be fixed?
- which deps should we choose?
- which open PRs need to be merged?
- ...?

**Comment by tseho** [comment]
I suggest you keep a list of open issues/PRs we are targeting for the v1.0 as a task list in your message, so we can know which ones are done and which ones needs to be done.

We can then discuss in separate issues different ideas/suggestions and you can decide if they are included in the roadmap list.

I started with #226

**Comment by DavidBadura** [comment]
I would now simply release the 1.0.0 version and work on the next version with bc breaks. We need to move forward ;-)

**Comment by DavidBadura** [comment]
just released v1.0.0 https://github.com/simplethings/EntityAudit/releases/tag/v1.0.0
