### ISSUE TITLE
SQL Server and sequence name

### ISSUE THREAD

**Issue by dlegatt** [simplethings/EntityAudit#230]
I have to use SQL Server for my database and am running into an error.  In LogRegisionsListener::getRevisionId(), there is a check to see if the platform supports sequences, which the SqlServer2012 platform does, but then it calls getIdentitySequenceName, which the SqlServerPlatform does not implement, so an exception is thrown.

**Comment by DavidBadura** [comment]
I think it is an issue in doctrine dbal. Or can you tell us how to solve it?

**Comment by dlegatt** [comment]
It probably is a doctrine dbal issue.  I worked around it in my fork by removing the sequenceName generation starting on line 309 and instead have
`$this->revisionId = $this->conn->lastInsertId();`

**Comment by DavidBadura** [comment]
Can you create a PR so we can run our tests?

**Comment by dlegatt** [comment]
I have very little experience with GitHub outside of hosting my own projects.  Can you tell me what I need to do to make a PR for you?

**Comment by dlegatt** [comment]
I made a PR, but it looks like it makes the tests fail

**Comment by smoench** [comment]
This is an issue with doctrine dbal and is maybe related to https://github.com/doctrine/dbal/issues/2467.
It should be fixed in dbal not in entity-audit.

**Comment by DavidBadura** [comment]
it should be solved in dbal (doctrine/dbal#2467)
