### ISSUE TITLE
Change comment field not present.

### ISSUE THREAD

**Issue by theantichris** [simplethings/EntityAudit#235]
After installing the bundle and updated my schema there change comment field in the revision table is not present, the other fields are.

**Comment by smoench** [comment]
@theantichris Could you provide some more information about your problem? An example project or a test case would be great.

**Comment by theantichris** [comment]
I went with my own implementation so I don't have this setup anymore. I didn't do anything other than install the bundle and update the schema using the command. The database column for the comments wasn't part of the table.
