### ISSUE TITLE
Regression: Loading revision data fails on entities with empty on-to-one associations

### ISSUE THREAD

**Issue by soerenbernstein** [simplethings/EntityAudit#237]
Updating from 0.7 to 0.9.2 I have trouble getting my revisions. After some testing I figured out this was introduced in 0.8. 

I my case I have a Customer entity which has a bidirectional association with my User entity called user with Customer being the owning side. It also has an additional unidirectional associations with User called registeringUser. Not all of my Users do have an associated Customer entity. 

Trying to load a revision of a Customer entity will result in a NoRevisionFoundException because AuditReader::find fails to load the non-existing Customer entity from the inverse side of the associated User entity.

I may be wrong, but I think the NoRevisionFoundException should only be thrown if this is the root entity. For any (optional) associated entities this exception should not be thrown.

**Comment by DavidBadura** [comment]
Hey, thank you for reporting! Can you check if the error exists in master too? I think we have fixed it with https://github.com/simplethings/EntityAudit/pull/218

**Comment by soerenbernstein** [comment]
Tried that, but sorry no luck.

**Comment by DavidBadura** [comment]
Do you know which commit introduced the error?

**Comment by soerenbernstein** [comment]
No, sorry. But it worked in 0.7 and is broken in 0.8.

**Comment by peschee** [comment]
Would probably be easy to find out with a `git bisect` and a working / failing test, given we know it is between 0.7 and 0.8.

**Comment by DavidBadura** [comment]
Should be solved by #227
