### ISSUE TITLE
Start using EntityAudit with existed DB

### ISSUE THREAD

**Issue by muspelheim** [simplethings/EntityAudit#238]
Hello, can you please provide any way to indexing existing DB? I don't have initial revisions for my object, and my Audit don't work, please help me.

**Comment by smoench** [comment]
@muspelheim Could you provide some more information about your problem? What exactly is not working? Any exception?

**Comment by smoench** [comment]
@muspelheim Might be fixed with #227. Fell free to open this issue again if your problem still exists and you could provide us more information.
