### ISSUE TITLE
Have a method to get only changed properties

### ISSUE THREAD

**Issue by Soullivaneuh** [simplethings/EntityAudit#248]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

The `AuditReader::diff` is great (and will be event better once #130 will be resolved), but if we wanted to get only changed property, we have to walk onto the returned array and make a `if ('' !== $property['same'])` each time.

This can be redundant if used on multiple part.

It would be great to have a method returning only changed properties.

I don't know for the name. Maybe `AuditReader::revealDiff`? Of maybe simply add a boolean parameter to `AuditReader::diff` to tells which result we want.

**Comment by DavidBadura** [comment]
Why don't we change it directly? Why do we need the properties that have not changed? Do we have a usecase?

**Comment by Soullivaneuh** [comment]
Yes, by yourself! :trollface: 

Ref: https://github.com/simplethings/EntityAudit/blob/master/src/SimpleThings/EntityAudit/Resources/views/Audit/compare.html.twig

Also use by sonata admin for the same kind of thing.

I think both are interesting, depending of the use case.

**Comment by DavidBadura** [comment]
okay :+1:
