### ISSUE TITLE
SQL syntax error when viewing revisions on entities with MySQL reserved yet quoted field names.

### ISSUE THREAD

**Issue by bobemoe** [simplethings/EntityAudit#26]
Entity with fields \`to\` and \`from\` produces invalid SQL due to not being quoted is the AS part.

Fields on entity are defined as such:
    /**
     * @var string $to
     * @ORM\Column(name="\`to\`", type="string", length=255)
     */
    private $to;      

SQL errors:

SELECT e.revtype, id AS id, name AS name, \`to\` AS to, \`from\` AS from, subject AS subject, body AS body FROM MailTemplate_audit e WHERE e.rev = ?' with params {"1":"4"}: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'to, \`from\` AS from, subject AS subject, body AS body FROM MailTemplate_audit e W' at line 1 (uncaught exception)

Quick (but untested for side affects)  fix is to comment out the end of line 222 of SimpleThings\EntityAudit\AuditReader (https://github.com/simplethings/EntityAudit.git 60a5bcb61a43fc4360ff5190cb4b5e63864fc3b7)

                $columnList .= ', ' . $class->getQuotedColumnName($field, $this->platform);// .' AS ' . $field;

EDIT: Correct formatting for clarity (\`to\` and \`from\` was showing as `to` and `from`)

**Comment by andrewtch** [comment]
@bobemoe , this should be fixed by now. Please re-check or close.

**Comment by bobemoe** [comment]
I no longer maintain the project that this affected so can't easily test.  I will close this issue. Thanks.
