### ISSUE TITLE
Undefined index when i delete an entity which is audit

### ISSUE THREAD

**Issue by psylo31** [simplethings/EntityAudit#31]
Notice: Undefined index: titre in MyPath\vendor\simplethings\entity-audit-bundle\src\SimpleThings\EntityAudit\EventListener\LogRevisionsListener.php line 206

Entity User :

/**
     * @ORM\OneToOne(targetEntity="MyProject\ReveBundle\Entity\Reve", cascade={"persist", "remove"})
     */
    protected $reve;

Action in my Reve repository to remove :

$user->setReve();
$this->_em->persist($user);
$this->_em->remove($reve);
$this->_em->flush();

It's work when the entity is not audit.

Thanks for you help

**Comment by andrewtch** [comment]
@psylo31 , @rickard2 , thsi should be fixed by now. Can you test?

**Comment by CountZero1981** [comment]
Seems that it fixed in latest build. I've had this problem in SonataAdminBundle and it disappeared after update.

**Comment by andrewtch** [comment]
I'm closing this as #117 actually works with no exception. Please comment if you find a way on how to repeat the behavior above.
